name: continuous integration
on: [push]
jobs:
  build:
    name: build, test and upload artifacts
    runs-on: ubuntu-24.04-arm
    container: arm64v8/amazonlinux:2023
    steps:
      - run: dnf install -y git tar gzip make cmake gcc14 gcc14-c++
      - uses: actions/checkout@v7
      - run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc14-gcc -DCMAKE_CXX_COMPILER=gcc14-g++
      - run: cmake --build build
      - run: ctest --test-dir build --output-on-failure
      - uses: actions/upload-artifact@v7
        with:
          name: example
          path: build/example/bootstrap
